// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_princess/test/data/repository/comment_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_princess/data/data_source/comment_remote_data_source.dart'
    as _i2;
import 'package:flutter_princess/data/dto/comment_dto.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CommentRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentRemoteDataSource extends _i1.Mock
    implements _i2.CommentRemoteDataSource {
  MockCommentRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CommentDto>> fetchComments(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchComments, [postId]),
            returnValue: _i3.Future<List<_i4.CommentDto>>.value(
              <_i4.CommentDto>[],
            ),
          )
          as _i3.Future<List<_i4.CommentDto>>);

  @override
  _i3.Future<void> addComment(_i4.CommentDto? comment) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [comment]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateComment(_i4.CommentDto? comment) =>
      (super.noSuchMethod(
            Invocation.method(#updateComment, [comment]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
