// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_princess/test/presentation/pages/home_page/home_page_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_princess/domain/entity/post.dart' as _i4;
import 'package:flutter_princess/domain/usecase/delete_post_usecase.dart'
    as _i6;
import 'package:flutter_princess/domain/usecase/fetch_posts_usecase.dart'
    as _i2;
import 'package:flutter_princess/domain/usecase/toggle_like_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FetchPostsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchPostsUseCase extends _i1.Mock implements _i2.FetchPostsUseCase {
  MockFetchPostsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Post>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
          )
          as _i3.Future<List<_i4.Post>>);
}

/// A class which mocks [ToggleLikeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleLikeUseCase extends _i1.Mock implements _i5.ToggleLikeUseCase {
  MockToggleLikeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [postId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [DeletePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeletePostUseCase extends _i1.Mock implements _i6.DeletePostUseCase {
  MockDeletePostUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [postId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
